### ISSUE TITLE
Would you consider releasing under Public Domain?

### ISSUE THREAD

**Issue by midrare** [wthe22/batchlib#1]
Usually, you'd use something like this by copying and paste little snippets into your own code. But MIT requires you to include the copyright notice with every use, which would mean you have to be tracking every snippet you use. And if you modify a snippet, you'd have to keep track of that too.

Would you consider a public domain license? Something like the [Unlicense](https://choosealicense.com/licenses/unlicense/)?

**Comment by wthe22** [comment]
yeah maintaining copyright notice for this kind of work would be unnecessary. will remove copyright notice requirement
